### ISSUE TITLE
Readiness probe is failing

### ISSUE THREAD

**Issue by arghya88** [making/uaa-on-kubernetes#1]
I tried to deploy this in Kubernetes but its failing with Readiness probe failed: Get https://100.96.2.31:8443/healthz: dial tcp 100.96.2.31:8443: connect: connection refused

**Comment by eskuai** [comment]
Hello

Just increase values ...

can you get to run it?

i can't connect from outter

````
  readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 10
          failureThreshold: 10
          periodSeconds: 40
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 30
          failureThreshold: 10
      volumes:
````
